// <auto-generated />
using System;
using FabrikaBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FabrikaBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307133535_AddCurrentStockToProducts")]
    partial class AddCurrentStockToProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("FabrikaBackend.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "firmaIsmi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "mail");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "isimSoyisim");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "tel");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "is_used");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "machine_name");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Machines");

                    b.HasAnnotation("Relational:JsonPropertyName", "machines");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<double>("EstimatedDays")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "estimated_days");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "quantity");

                    b.Property<double>("SalePrice")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "sale_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<double>("TotalCost")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "total_cost");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("AbsenteeismDays")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "devamsizlik_gun");

                    b.Property<double>("AverageDailyProduction")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "ortalama_gunluk_uretim");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "egitim_sertifikalari");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "companyId");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "departman");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "acil_durum_kisi");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "acil_durum_tel");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "ad");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "ise_giris_tarihi");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "aktif");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "soyad");

                    b.Property<double>("OvertimeHours")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "fazla_mesai_saat");

                    b.Property<double>("PerformanceScore")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "performans_puani");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "telefon");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "pozisyon");

                    b.Property<int>("RemainingLeave")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "kalan_izin");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "maas");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "tcNo");

                    b.Property<int>("TotalAnnualLeave")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "yillik_izin_hakki");

                    b.Property<int>("UsedLeave")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "kullanilan_izin");

                    b.HasKey("Id");

                    b.ToTable("Personnels");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<double>("BaseCost")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "base_cost");

                    b.Property<double>("BrutAgirlikKg")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "brut_agirlik_kg");

                    b.Property<int>("CalisanSayisi")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "calisan_sayisi");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "current_stock");

                    b.Property<int>("GunlukUretim")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "gunluk_uretim");

                    b.Property<string>("HamMadde")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "ham_madde");

                    b.Property<bool>("HasHeatTreatment")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "has_heat_treatment");

                    b.Property<double>("HurdaOrani")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "hurda_orani");

                    b.Property<string>("MalzemeTipi")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "malzeme_tipi");

                    b.Property<double>("MalzemeVerimi")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "malzeme_verimi");

                    b.Property<double>("NetAgirlikKg")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "net_agirlik_kg");

                    b.Property<string>("PresKategorisi")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "pres_kategorisi");

                    b.Property<string>("UrunKodu")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "urun_kodu");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Stock", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "kod");

                    b.Property<double>("Capacity")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "kapasite");

                    b.Property<double>("CriticalLevel")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "kritik");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "ad");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "miktarSayi");

                    b.Property<string>("QuantityText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "miktar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "durum");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "birimMaliyet");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "birimFiyat");

                    b.HasKey("Code");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FabrikaBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "role");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Machine", b =>
                {
                    b.HasOne("FabrikaBackend.Models.Product", null)
                        .WithMany("Machines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FabrikaBackend.Models.Product", b =>
                {
                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
