// <auto-generated />
using System;
using FabrikaBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FabrikaBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FabrikaBackend.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "firmaIsmi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "mail");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "isimSoyisim");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tel");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Expense", b =>
                {
                    b.Property<string>("GiderAdi")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "gider_adi");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "companyId");

                    b.Property<string>("GiderTipi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "gider_tipi");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "tarih");

                    b.Property<double>("Tutar")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "tutar");

                    b.HasKey("GiderAdi");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Income", b =>
                {
                    b.Property<string>("GelirAdi")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "gelir_adi");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "companyId");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "tarih");

                    b.Property<double>("Tutar")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "tutar");

                    b.HasKey("GelirAdi");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "details");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "machine_name");

                    b.Property<string>("ProductUrunKodu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductUrunKodu");

                    b.ToTable("Machines");

                    b.HasAnnotation("Relational:JsonPropertyName", "machines");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "order_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<double>("EstimatedDays")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "estimated_hour");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "musteri_adi");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "quantity");

                    b.Property<double>("SalePrice")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "sale_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<double>("TotalCost")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "total_cost");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "urun_adi");

                    b.Property<string>("UrunKodu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "urun_kodu");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Personnel", b =>
                {
                    b.Property<string>("TcNo")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasAnnotation("Relational:JsonPropertyName", "tcNo");

                    b.Property<int>("AbsenteeismDays")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "devamsizlik_gun");

                    b.Property<double>("AverageDailyProduction")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "ortalama_gunluk_uretim");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "egitim_sertifikalari");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "acil_durum_kisi");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "acil_durum_tel");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "ad");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "ise_giris_tarihi");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "soyad");

                    b.Property<decimal>("MealAllowance")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "yemek_ucreti");

                    b.Property<double>("OvertimeHours")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "fazla_mesai_saat");

                    b.Property<double>("PerformanceScore")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "performans_puani");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasAnnotation("Relational:JsonPropertyName", "telefon");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "pozisyon");

                    b.Property<int>("RemainingLeave")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "kalan_izin");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "maas");

                    b.Property<int>("TotalAnnualLeave")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "yillik_izin_hakki");

                    b.Property<decimal>("TransportAllowance")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "yol_ucreti");

                    b.Property<int>("UsedLeave")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "kullanilan_izin");

                    b.HasKey("TcNo");

                    b.ToTable("Personnels");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Product", b =>
                {
                    b.Property<string>("UrunKodu")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "urun_kodu");

                    b.Property<double>("BaseCost")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "base_cost");

                    b.Property<double?>("BirimUretimSuresiSaat")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "birim_uretim_suresi_saat");

                    b.Property<double>("BrutAgirlikKg")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "brut_agirlik_kg");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "current_stock");

                    b.Property<string>("HamMadde")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "ham_madde");

                    b.Property<double>("HurdaOrani")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "hurda_orani");

                    b.Property<string>("MalzemeTipi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "malzeme_tipi");

                    b.Property<double>("NetAgirlikKg")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "net_agirlik_kg");

                    b.Property<string>("PresKategorisi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "pres_kategorisi");

                    b.Property<double?>("SalePrice")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "sale_price");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "urun_adi");

                    b.HasKey("UrunKodu");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Stock", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "kod");

                    b.Property<double>("Capacity")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "kapasite");

                    b.Property<double>("CriticalLevel")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "kritik");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "ad");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "miktarSayi");

                    b.Property<string>("QuantityText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "miktar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "durum");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "birimMaliyet");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "birimFiyat");

                    b.HasKey("Code");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FabrikaBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Machine", b =>
                {
                    b.HasOne("FabrikaBackend.Models.Product", null)
                        .WithMany("Machines")
                        .HasForeignKey("ProductUrunKodu");
                });

            modelBuilder.Entity("FabrikaBackend.Models.Product", b =>
                {
                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
