/**
 * Müşteriler sayfası için mock veri. idKod siparişlerdeki musteriId ile eşleşir.
 * tip: 'kurumsal' | 'bireysel'
 */
export const MUSTERI_LISTESI = [
  {
    id: 1,
    idKod: 'M1',
    ad: 'Ahmet',
    soyad: 'Yılmaz',
    email: 'ahmet.yilmaz@abcoto.com',
    telefon: '0212 555 0101',
    tip: 'kurumsal',
    unvan: 'ABC Otomotiv A.Ş.',
  },
  {
    id: 2,
    idKod: 'M2',
    ad: 'Fatma',
    soyad: 'Demir',
    email: 'fatma.demir@xyzmetal.com',
    telefon: '0312 555 0202',
    tip: 'kurumsal',
    unvan: 'XYZ Metal San. Tic. Ltd.',
  },
  {
    id: 3,
    idKod: 'M3',
    ad: 'Mehmet',
    soyad: 'Kaya',
    email: 'mehmet.kaya@delta.com',
    telefon: '0216 555 0303',
    tip: 'kurumsal',
    unvan: 'Delta Endüstri A.Ş.',
  },
  {
    id: 4,
    idKod: 'M4',
    ad: 'Zeynep',
    soyad: 'Öz',
    email: 'zeynep.oz@omega.com',
    telefon: '0232 555 0404',
    tip: 'kurumsal',
    unvan: 'Omega Makine Ltd.',
  },
  {
    id: 5,
    idKod: 'B1',
    ad: 'Can',
    soyad: 'Öztürk',
    email: 'can.ozturk@mail.com',
    telefon: '0532 111 2233',
    tip: 'bireysel',
    unvan: null,
  },
  {
    id: 6,
    idKod: 'B2',
    ad: 'Elif',
    soyad: 'Arslan',
    email: 'elif.arslan@mail.com',
    telefon: '0543 444 5566',
    tip: 'bireysel',
    unvan: null,
  },
  {
    id: 7,
    idKod: 'M5',
    ad: 'Serkan',
    soyad: 'Aydın',
    email: 'serkan.aydin@betoncelik.com',
    telefon: '0212 555 9900',
    tip: 'kurumsal',
    unvan: 'Beton Çelik İnş. A.Ş.',
  },
];
